[package]
name = "cargo-bin"
edition = "2024"
license = "MIT"

[lints.clippy]
pedantic = "deny"

[dependencies]
cargo-run-bin = { git = "https://github.com/matanlurey/cargo-run-bin.git", branch = "forked", features = [
  "cli",
] }
